#!/usr/bin/env python3
"""Masti dialogues - 6 per button, short, college-relate, proxy-free, respect-aware."""
import hashlib
DIALOGUES = {
    "ABSENT_D": [
        "Bunk maare din, yaad hai? 😜",
        "Gayab din ki list! 👻",
        "Absent ka hisaab! 🚫",
        "Kahan the us din? 🤔",
        "Bunk ke din! 😴",
        "Gayab ka record! 📉",
    ],
    "ABSENT_LIST": [
        "Bunk gang pakdi gayi! 😜",
        "Gayab gang, kaha ho? 👻",
        "Absent ka dhamaka! 🚫",
        "Bunk maara, pakde gaye! 😅",
        "Gayab ka hisaab! 📉",
        "Absent ki list! 🕵️",
    ],
    "BAND": [
        "Sunday ka aaram, pure din! 😎",
        "Band din gin lo! 🔒",
        "Kitne din band? 🚪",
        "Band ka hisaab! 🧮",
        "Band din ka maza! 😴",
        "Band gin lo! 📅",
    ],
    "CHANGE_NO": [
        "Sab sahi hai! ✅",
        "No change, aage chalo! ➡️",
        "Perfect hai! 👌",
        "Chalo aage! 🚀",
        "Ok, lock karte hain! 🔒",
        "Sab set! 😎",
    ],
    "CHANGE_YES": [
        "Badlav karte hain! 🔄",
        "Haan, sudhar lete hain! ✏️",
        "Change on! 🛠️",
        "Chalo theek karte hain! 😊",
        "Haan, naya karte hain! ✨",
        "Ok, change mode! 🔧",
    ],
    "CHHUTTI": [
        "Kambal jeeta, class haari! 🛌",
        "Photocopy kal, aaj sone de! 📸",
        "Lab bunk, smart move! 🧪",
        "Canteen me haziri! 🍔",
        "Back-bencher ka hak! 😴",
        "Network issue bol! 📵",
    ],
    "CHUTTI_TOTAL": [
        "Chhutti ka hisaab, bunk ka maza! 😴",
        "Kitni chhutti, batau? 📊",
        "Chhutti ka stock! 📦",
        "Bunk ka hisaab! 🛌",
        "Chhutti gin lo! 🧮",
        "Kitne din ghar? 🏠",
    ],
    "COMPLETE_LIST": [
        "Full class, ek jhalak me! 📋",
        "Poori class hazir! 🎓",
        "Sab ek saath, maza aaya! 🎉",
        "Complete ka jadoo! ✨",
        "Sabka hisaab, ek jagah! 🧮",
        "Full list, full masti! 🌟",
    ],
    "COUNT": [
        "Poori class ka hisaab! 👥",
        "Kitne sher, kitne ghayal! 😜",
        "Gin le, sab hazir! 📊",
        "Class ka census! 📋",
        "Bheed ka hisaab! 🧮",
        "Count me masti! 🎉",
    ],
    "CS": [
        "CS wale coding king! 💻",
        "CS = future ready! 🚀",
        "Coder gang! 😎",
        "CS wale rock! 🎸",
        "Logic wale log! 🧠",
        "Tech ke hero! 🌟",
    ],
    "CUSTOM": [
        "Date batao, kissa sunata hu! 🕵️",
        "Konsi tareekh? Batao! 📅",
        "Date ka raaz khulega! 🔍",
        "Tareekh bolo, hisaab doon! 🧮",
        "Custom date ka jadoo! ✨",
        "Date pucho, jawab doon! 💬",
    ],
    "EC": [
        "EC wale circuit master! 🔌",
        "EC = current flow! ⚡",
        "Signal ke sikandar! 📡",
        "EC wale genius! 🤓",
        "Chip wale hero! 💾",
        "EC ka tadka! 🎛️",
    ],
    "EXIT": [
        "Dil tod ke ja rahe ho! 💔",
        "Phir aana, tang karunga! 😜",
        "Bye dost, miss karunga! 👋",
        "Are nikal gaye! 😅",
        "Chalte ho? Ok bye! 🙏",
        "Exit ka dukh! 😢",
    ],
    "EXIT_LEAVE": [
        "Chalte hain, phir milenge! 👋",
        "Exit ka time! 🚪",
        "Nikal chale! 🏃",
        "Bye bye! 👋",
        "Chalo, alvida! 🙏",
        "Exit successful! ✅",
    ],
    "GAYA": [
        "Gaye din gin lo, topper! 🚌",
        "Kitne din gaye, yaad hai? 🤔",
        "College ke din! 🏫",
        "Haziri ke din! 📅",
        "Gaye din ka hisaab! 🧮",
        "Din gino, maza lo! 😎",
    ],
    "HOLIDAY": [
        "Holiday hai, maze karo! 🏖️",
        "College band, dil khush! 😁",
        "Aaj chhutti, kal padhai! 🎉",
        "Gate band, masti on! 🥳",
        "Holiday ka jashn! 🎊",
        "Band hai, chill karo! 😎",
    ],
    "IT": [
        "IT wale jugaadu! 💡",
        "IT = innovation! ✨",
        "Network ke boss! 🌐",
        "IT wale smart! 🧠",
        "System ke star! ⭐",
        "IT ka jalwa! 🔥",
    ],
    "KHULA": [
        "Khula band ka game! 🏫",
        "Kitne din khula? 🔓",
        "College khula kitna? 📖",
        "Khule din gin lo! 🗓️",
        "Khula ka hisaab! 📊",
        "Khula din ka maza! 😎",
    ],
    "KNOW": [
        "ID bhool gaye? Lo yaad dila diya! 🪪",
        "Yehi hai pehchan! 🤫",
        "ID ka raaz khula! 🔑",
        "Pehchan patra hazir! 📇",
        "ID ka jadoo! ✨",
        "Yaad dila diya! 💡",
    ],
    "LOOKUP": [
        "Jasoosi shuru, record khulega! 🕵️",
        "Kiska data nikalna hai? 🔍",
        "Detective mode on! 🧐",
        "Record ka raaz khulega! 📂",
        "Khoj shuru! 🔎",
        "Data ka jadoo! ✨",
    ],
    "MAZE": [
        "Aaj maze karo, kal padhai! 🎉",
        "Chhutti hai, chill maro! 😎",
        "Masti mode ON! 🥳",
        "Maze ka din! 🎊",
        "Chill ka time! 😁",
        "Masti hi masti! 🌈",
    ],
    "ME": [
        "ME wale machine hero! ⚙️",
        "ME = solid! 🔩",
        "Workshop ke king! 🛠️",
        "ME wale strong! 💪",
        "Engine wale dost! 🚜",
        "ME ka dum! 🔧",
    ],
    "MENU": [
        "Khul gaya khazana! 🗝️",
        "Saare raaz yahan! 🤫",
        "Menu khula, maza aaya! 📋",
        "Options ki baraat! 🎉",
        "Khazana khula! 💎",
        "Menu ka jadoo! ✨",
    ],
    "MONTH": [
        "Is mahine ka full scene! 📅",
        "Mahine ka hisaab! 🗓️",
        "Is mahine kya hua? 🤔",
        "Month ka report! 📊",
        "Mahine ka jadoo! ✨",
        "Is mahine ka kissa! 📖",
    ],
    "NO": [
        "Arre yaar, soch lo! 🤔",
        "Koi baat nahi, phir milenge! 👋",
        "Theek hai, bye dost! 😊",
        "Chalo, kabhi aur! 🙏",
        "Ok, intezaar rahega! ⏳",
        "Bye, yaad rakhna! 💙",
    ],
    "NOTICE": [
        "Notice aaya, bachche khush! 📢",
        "Chhutti ka ilan, nacho! 💃",
        "Notice board chamka! ✨",
        "Khabar aayi, maze aaye! 🎉",
        "Notice update, sab khush! 😊",
        "Naya notice, naya maza! 📄",
    ],
    "PCT": [
        "Percent dekho, BP badhao! 😅",
        "75% ka dar, ab hisaab! 📊",
        "Kitna aaye, dekho! 👀",
        "Percent ka khel! 🎲",
        "Number bole! 🔢",
        "Result ka time! ⏰",
    ],
    "PRESENT": [
        "HOD shocked, topper nikla! 😎",
        "CR bhi fail, tu pass! 🤣",
        "Canteen samosa pakka! 😋",
        "Front bench hero! 🧐",
        "Viva bach gaya! 📚",
        "Bunk me akela sher! 🦸",
    ],
    "PRESENT_D": [
        "Haziri wale din, hero wale! ⭐",
        "Present ka jalwa! ✅",
        "Hazir din ki list! 📋",
        "Aaye din yaad! 😎",
        "Present ke din! 🎉",
        "Haziri ka hisaab! 📊",
    ],
    "PRESENT_LIST": [
        "Hazir gang on fire! 🔥",
        "Present wale rock! 😎",
        "Hazir log, topper log! 🏆",
        "Aaye log, chha gaye! 🌟",
        "Present ka jalwa! ✅",
        "Haziri ka dum! 💪",
    ],
    "PROOF": [
        "Saboot hazir, aankhein kholo! 👀",
        "Proof aaya, sach khula! 📄",
        "Dekho, sach yahan hai! 🔍",
        "Saboot ka dhamaka! 💥",
        "Proof ka jalwa! ✨",
        "Sach ka samna! 😎",
    ],
    "RECALL": [
        "Wapas lete hain! ↩️",
        "Delete ka jadoo! 🗑️",
        "Galti sudharo! 🔄",
        "Wapas kheecho! ↪️",
        "Recall ka dum! 💪",
        "Delete mode on! 🧹",
    ],
    "RECALL_NO": [
        "Rehne do, chhodo! ❌",
        "Nahi, rehne do! 🙏",
        "Chhodo, theek hai! 😊",
        "Nahi chahiye! 🚫",
        "Rehne do yaar! 🤚",
        "Cancel kar do! ⏹️",
    ],
    "RECALL_YES": [
        "Haan, uda do! ✅",
        "Delete pakka! 💥",
        "Uda diya jaye! 🚀",
        "Haan, clean karo! 🧹",
        "Pakka delete! 👍",
        "Haan, hatao! 🗑️",
    ],
    "STUDENT_LIST": [
        "List nikalo, hero dikhao! 📋",
        "Poori list, roll wise! 📜",
        "Students ki baraat! 🎉",
        "List ka jadoo! ✨",
        "Sabki list hazir! 👥",
        "Roll wise sajaya! 📊",
    ],
    "TODAY": [
        "Aaj ka din! 📅",
        "Aaj ki tareekh! 🗓️",
        "Aaj ka jadoo! ✨",
        "Aaj ka din khaas! 🌟",
        "Aaj ka scene! 🎬",
        "Aaj ka mauka! 🎯",
    ],
    "Y1": [
        "First year, naya josh! 🌱",
        "Naye ho, chha jao! ✨",
        "Fresher ka jalwa! 😎",
        "Pehla saal, masti shuru! 🎉",
        "Naya safar! 🚀",
        "First year rock! 🎸",
    ],
    "Y2": [
        "Second year, set ho gaye! 😎",
        "Ab toh purane ho! 😉",
        "2nd year ka swag! 😏",
        "Experience aa gaya! 🌟",
        "Second year hero! 💪",
        "Ab toh senior! 👑",
    ],
    "Y3": [
        "Third year, expert! 🎓",
        "Ab toh pro ho! 😎",
        "3rd year ka dum! 🔥",
        "Senior ka swag! 👑",
        "Placement ki taiyaari! 💼",
        "Third year rock! 🚀",
    ],
    "Y4": [
        "Final year, last masti! 🎓",
        "Akhir saal, yaadgar banao! 🌟",
        "Final ka josh! 🔥",
        "Last year, full power! 💪",
        "Degree paas! 🎉",
        "Final year hero! 👑",
    ],
    "YES": [
        "Chalo shuru karte hain! 🚀",
        "Hero banne chale! 😎",
        "Registration on! 🎉",
        "Chalo form bharte hain! 📝",
        "Shabash, himmat dikhai! 💪",
        "Chalo, naya safar! 🌟",
    ],
}

def masti_for(key: str, day: str) -> str:
    """Roz alag dialogue: hash(day+key) % 6, din bhar same."""
    pool = DIALOGUES.get(key, [""])
    if not pool:
        return ""
    h = int(hashlib.md5((day+key).encode()).hexdigest()[:8], 16)
    return pool[h % len(pool)]
